# Generated by Django 5.2.17 on 2026-09-12 21:54

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='categoria',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('nome'), name='categoria_nome_unico_ci', violation_error_message='Já existe uma categoria com esse nome.'),
        ),
        migrations.AddConstraint(
            model_name='prato',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('nome'), name='prato_nome_unico_ci', violation_error_message='Já existe um item do cardápio com esse nome.'),
        ),
    ]
