# Generated by Django 5.2.17 on 2026-09-15 00:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0002_categoria_categoria_nome_unico_ci_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comboitem',
            name='quantidade',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, 'A quantidade mínima é 1.')]),
        ),
        migrations.AddConstraint(
            model_name='comboitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantidade__gte', 1)), name='comboitem_quantidade_minima'),
        ),
    ]
