# Generated by Django 5.2.17 on 2026-09-15 23:50

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0003_alter_comboitem_quantidade_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='combo',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('nome'), name='combo_nome_unico_ci', violation_error_message='Já existe um combo com esse nome.'),
        ),
        migrations.AddConstraint(
            model_name='combo',
            constraint=models.CheckConstraint(condition=models.Q(('preco__gte', 0)), name='combo_preco_nao_negativo', violation_error_message='O preço não pode ser negativo.'),
        ),
        migrations.AddConstraint(
            model_name='prato',
            constraint=models.CheckConstraint(condition=models.Q(('preco__gte', 0)), name='prato_preco_nao_negativo', violation_error_message='O preço não pode ser negativo.'),
        ),
    ]
