# Generated by Django 5.2.17 on 2026-09-12 19:28

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cardapio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=20, unique=True)),
                ('tipo', models.CharField(choices=[('MESA', 'Mesa'), ('VIAGEM', 'Viagem'), ('BALCAO', 'Balcão')], default='MESA', max_length=10)),
                ('responsavel', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('FECHADA', 'Fechada'), ('CANCELADA', 'Cancelada')], default='ABERTA', max_length=10)),
                ('aberta_em', models.DateTimeField(auto_now_add=True)),
                ('fechada_em', models.DateTimeField(blank=True, null=True)),
                ('taxa_servico', models.BooleanField(default=False)),
                ('desconto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('forma_pagamento', models.CharField(blank=True, choices=[('DINHEIRO', 'Dinheiro'), ('PIX', 'Pix'), ('DEBITO', 'Débito'), ('CREDITO', 'Crédito')], max_length=10)),
                ('total_pago', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'verbose_name': 'comanda',
                'verbose_name_plural': 'comandas',
                'ordering': ['-aberta_em'],
            },
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacao', models.CharField(max_length=20, unique=True)),
                ('capacidade', models.PositiveIntegerField(default=4)),
                ('ativa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'mesa',
                'verbose_name_plural': 'mesas',
                'ordering': ['identificacao'],
            },
        ),
        migrations.CreateModel(
            name='ItemComanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observacao', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_PREPARO', 'Em preparo'), ('PRONTO', 'Pronto'), ('ENTREGUE', 'Entregue'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=12)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('comanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='atendimento.comanda')),
                ('combo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cardapio.combo')),
                ('prato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cardapio.prato')),
            ],
            options={
                'verbose_name': 'item da comanda',
                'verbose_name_plural': 'itens da comanda',
                'ordering': ['criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ItemAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cardapio.prato')),
                ('item_comanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adicionais', to='atendimento.itemcomanda')),
            ],
            options={
                'verbose_name': 'adicional',
                'verbose_name_plural': 'adicionais',
            },
        ),
        migrations.AddField(
            model_name='comanda',
            name='mesa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comandas', to='atendimento.mesa'),
        ),
        migrations.AddConstraint(
            model_name='itemcomanda',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('combo__isnull', True), ('prato__isnull', False)), models.Q(('combo__isnull', False), ('prato__isnull', True)), _connector='OR'), name='item_prato_ou_combo'),
        ),
    ]
