# Generated by Django 5.2.17 on 2026-09-15 00:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0002_alter_itemadicional_preco_unitario_and_more'),
        ('cardapio', '0003_alter_comboitem_quantidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcomanda',
            name='quantidade',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, 'A quantidade mínima é 1.')]),
        ),
        migrations.AddConstraint(
            model_name='itemcomanda',
            constraint=models.CheckConstraint(condition=models.Q(('quantidade__gte', 1)), name='item_quantidade_minima'),
        ),
    ]
