# Generated by Django 5.2.17 on 2026-09-15 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0003_alter_itemcomanda_quantidade_and_more'),
        ('cardapio', '0004_combo_combo_nome_unico_ci_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='comanda',
            constraint=models.CheckConstraint(condition=models.Q(('desconto__gte', 0)), name='comanda_desconto_nao_negativo', violation_error_message='O desconto não pode ser negativo.'),
        ),
        migrations.AddConstraint(
            model_name='comanda',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('mesa__isnull', False), ('tipo', 'MESA')), models.Q(models.Q(('tipo', 'MESA'), _negated=True), ('mesa__isnull', True)), _connector='OR'), name='comanda_mesa_conforme_tipo', violation_error_message='Comanda de mesa exige uma mesa; viagem e balcão não podem ter mesa'),
        ),
        migrations.AddConstraint(
            model_name='itemcomanda',
            constraint=models.CheckConstraint(condition=models.Q(('preco_unitario__isnull', True), ('preco_unitario__gte', 0), _connector='OR'), name='item_preco_nao_negativo'),
        ),
    ]
