# Generated by Django 5.2.17 on 2026-09-16 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0004_comanda_comanda_desconto_nao_negativo_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='mesa',
            constraint=models.CheckConstraint(condition=models.Q(('capacidade__gte', 1)), name='mesa_capacidade_minima', violation_error_message='A mesa precisa ter ao menos um lugar.'),
        ),
    ]
