# Generated by Django 5.2.17 on 2026-09-22 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0005_mesa_mesa_capacidade_minima'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcomanda',
            name='cancelado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemcomanda',
            name='motivo_cancelamento',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
