# Generated by Django 5.2.17 on 2026-09-23 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0007_preenche_motivo_cancelamento'),
        ('cardapio', '0004_combo_combo_nome_unico_ci_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='itemcomanda',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'CANCELADO'), _negated=True), models.Q(('motivo_cancelamento', ''), _negated=True), _connector='OR'), name='item_cancelado_tem_motivo', violation_error_message='Item cancelado precisa de um motivo.'),
        ),
    ]
